// ALIAS

###

// findByAgentId
GET http://localhost:8080/api/alias/jjkbjb HTTP/1.1

### 

// add
POST http://localhost:8080/api/alias HTTP/1.1
Content-Type: application/json

{
    "name": "Bill Nye",
    "persona": "Science man",
    "agentId": 2
}

###

// update
PUT http://localhost:8080/api/alias/7 HTTP/1.1
Content-Type: application/json

{   
    "aliasId": 7,
    "name": "Will",
    "persona": "Man",
    "agentId": 2
}

###

// delete
DELETE  http://localhost:8080/api/alias/2 HTTP/1.1
